In [2]:
import torch as tr

In [3]:
t1=tr.tensor(4)

t1.dtype

In [4]:
t1.dtype

torch.int64

In [5]:
t2= tr.tensor([[1,2,3],[4,5,6]])

In [6]:
t2.shape

torch.Size([2, 3])

In [7]:
x= tr.tensor(3.)
w= tr.tensor(4.,requires_grad = True)
b= tr.tensor(5., requires_grad= True)

In [9]:
y= w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [320]:
y.backward()

In [321]:
print(x.grad)
print(w.grad)
print(b.grad)

None
tensor(3.)
tensor(1.)


In [322]:
t3= tr.tensor(4.)
t4 = tr.tensor(5.,requires_grad=True)
t5 = tr.tensor(6.,requires_grad=True)

In [323]:
t= t3+t4
t.backward()

In [324]:
print(t.grad)

None


<ipython-input-324-9766b7f3a2f6>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(t.grad)


In [325]:
print(t3.grad)
print(t4.grad)

None
tensor(1.)


In [12]:
import numpy as np
import pandas as pd

In [13]:
n= np.array([[1,2,3],[2,3,5]])

In [14]:
z= tr.from_numpy(n)

In [15]:
z

tensor([[1, 2, 3],
        [2, 3, 5]], dtype=torch.int32)

In [16]:
y=z.numpy()

In [17]:
y

array([[1, 2, 3],
       [2, 3, 5]])

In [18]:
import seaborn as sb
import pandas as pd

In [19]:
data=sb.load_dataset('iris')

In [20]:
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [21]:
data= data.drop(columns=['species','petal_width'],axis=1)

In [22]:
data.head()

sepal_length  sepal_width  petal_length
0           5.1          3.5           1.4
1           4.9          3.0           1.4
2           4.7          3.2           1.3
3           4.6          3.1           1.5
4           5.0          3.6           1.4

In [36]:
X= data.drop(columns=['sepal_length'],axis=1).astype('float32')
Y=data['sepal_length'].astype('float32')

In [37]:
X=pd.DataFrame(X).to_numpy()

In [38]:
Y= pd.DataFrame(Y).to_numpy()

In [39]:
inputs= tr.from_numpy(X)
target = tr.from_numpy(Y)

In [71]:
print(inputs)

tensor([[3.5000, 1.4000],
        [3.0000, 1.4000],
        [3.2000, 1.3000],
        [3.1000, 1.5000],
        [3.6000, 1.4000],
        [3.9000, 1.7000],
        [3.4000, 1.4000],
        [3.4000, 1.5000],
        [2.9000, 1.4000],
        [3.1000, 1.5000],
        [3.7000, 1.5000],
        [3.4000, 1.6000],
        [3.0000, 1.4000],
        [3.0000, 1.1000],
        [4.0000, 1.2000],
        [4.4000, 1.5000],
        [3.9000, 1.3000],
        [3.5000, 1.4000],
        [3.8000, 1.7000],
        [3.8000, 1.5000],
        [3.4000, 1.7000],
        [3.7000, 1.5000],
        [3.6000, 1.0000],
        [3.3000, 1.7000],
        [3.4000, 1.9000],
        [3.0000, 1.6000],
        [3.4000, 1.6000],
        [3.5000, 1.5000],
        [3.4000, 1.4000],
        [3.2000, 1.6000],
        [3.1000, 1.6000],
        [3.4000, 1.5000],
        [4.1000, 1.5000],
        [4.2000, 1.4000],
        [3.1000, 1.5000],
        [3.2000, 1.2000],
        [3.5000, 1.3000],
        [3.6000, 1.4000],
        [3.0

In [128]:
w= tr.randn(1,2,requires_grad= True)
b= tr.randn(1,requires_grad=True)

In [129]:
print(b)
print(w)

tensor([0.7697], requires_grad=True)
tensor([[ 0.7660, -0.7891]], requires_grad=True)


In [79]:
def model(x):
   return x@w.t()+b

In [80]:
pred =model(inputs)

In [81]:
print(pred)

tensor([[4.9258],
        [4.3777],
        [4.6388],
        [4.4454],
        [5.0354],
        [5.2387],
        [4.8162],
        [4.7743],
        [4.2680],
        [4.4454],
        [5.1032],
        [4.7324],
        [4.3777],
        [4.5033],
        [5.5577],
        [5.8706],
        [5.4062],
        [4.9258],
        [5.1290],
        [5.2128],
        [4.6905],
        [5.1032],
        [5.2030],
        [4.5809],
        [4.6068],
        [4.2939],
        [4.7324],
        [4.8839],
        [4.8162],
        [4.5132],
        [4.4035],
        [4.7743],
        [5.5417],
        [5.6932],
        [4.4454],
        [4.6807],
        [4.9677],
        [5.0354],
        [4.4196],
        [4.7743],
        [4.9677],
        [3.6522],
        [4.6388],
        [4.8420],
        [5.0453],
        [4.3777],
        [5.1709],
        [4.5969],
        [5.1032],
        [4.7066],
        [3.2148],
        [3.2985],
        [3.0214],
        [2.5213],
        [2.8181],
        [2

In [82]:
diff =pred-target
diff

tensor([[-1.7418e-01],
        [-5.2233e-01],
        [-6.1186e-02],
        [-1.5458e-01],
        [ 3.5444e-02],
        [-1.6132e-01],
        [ 2.1619e-01],
        [-2.2570e-01],
        [-1.3196e-01],
        [-4.5458e-01],
        [-2.9681e-01],
        [-6.7581e-02],
        [-4.2233e-01],
        [ 2.0333e-01],
        [-2.4227e-01],
        [ 1.7059e-01],
        [ 6.2137e-03],
        [-1.7418e-01],
        [-5.7095e-01],
        [ 1.1282e-01],
        [-7.0947e-01],
        [ 3.1891e-03],
        [ 6.0298e-01],
        [-5.1909e-01],
        [-1.9323e-01],
        [-7.0610e-01],
        [-2.6758e-01],
        [-3.1607e-01],
        [-3.8381e-01],
        [-1.8684e-01],
        [-3.9647e-01],
        [-6.2570e-01],
        [ 3.4170e-01],
        [ 1.9322e-01],
        [-4.5458e-01],
        [-3.1930e-01],
        [-5.3230e-01],
        [ 1.3544e-01],
        [ 1.9557e-02],
        [-3.2570e-01],
        [-3.2300e-02],
        [-8.4784e-01],
        [ 2.3881e-01],
        [-1

In [83]:
def mse(tp,ty):
    diff = tp-ty
    return tr.sum(diff*diff)/diff.numel()
    

In [84]:
loss = mse (pred,target)

In [85]:
print(loss)

tensor(8.6186, grad_fn=<DivBackward0>)


In [86]:
loss.backward()

In [87]:
print(w)
print(w.grad)

tensor([[ 1.0963, -0.4188]], requires_grad=True)
tensor([[-13.8443, -23.8092]])


In [88]:
print(b)
print(b.grad)

tensor([1.6752], requires_grad=True)
tensor([-4.7809])


In [89]:
 with tr.no_grad():
        w-=w.grad * 1e-5
        b-=b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [90]:
print(w)
print(b)

tensor([[ 1.0964, -0.4186]], requires_grad=True)
tensor([1.6752], requires_grad=True)


In [92]:
for i in range(100):
    pred = model(inputs)
    loss = mse(pred,target)
    loss.backward()
    with tr.no_grad():
        w-=w.grad * 1e-5
        b-=b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()
        

In [93]:
pred = model(inputs)
loss = mse(pred,target)
print(loss)

tensor(7.8621, grad_fn=<DivBackward0>)


In [94]:
import torch.nn as nn

In [95]:
from torch.utils.data import TensorDataset

In [96]:
train_ds = TensorDataset(inputs,target)

In [97]:
train_ds

model

In [112]:
model = nn.Linear(2,1)

model.weight

In [113]:
model.weight

Parameter containing:
tensor([[-0.6332, -0.0540]], requires_grad=True)

In [114]:
model.bias

Parameter containing:
tensor([0.3510], requires_grad=True)

In [115]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.6332, -0.0540]], requires_grad=True),
 Parameter containing:
 tensor([0.3510], requires_grad=True)]

In [116]:
import torch.nn.functional as F

In [117]:
loss_fn = F.mse_loss

In [118]:
loss = loss_fn(model(inputs),target)

In [119]:
print(loss)

tensor(59.0625, grad_fn=<MseLossBackward>)


In [120]:
opt = tr.optim.SGD(model.parameters(),lr = 1e-5)

In [121]:
def fit(number_epochs , model , loss_fn, opt):
    
    for epoch in range(number_epochs):
        
        pred = model(inputs)
        
        loss = loss_fn(pred,target)
        
        loss.backward()
        
        opt.step()
        
        opt.zero_grad()
        
        
        if (epoch +1)%10 == 0:
            
            print('Epoch [{}/{}], Loss :{:.4f}'.format(epoch+1, number_epochs, loss.item()))

In [122]:
fit(500,model,loss_fn,opt)

Epoch [10/500], Loss :58.5250
Epoch [20/500], Loss :57.9337
Epoch [30/500], Loss :57.3485
Epoch [40/500], Loss :56.7694
Epoch [50/500], Loss :56.1963
Epoch [60/500], Loss :55.6292
Epoch [70/500], Loss :55.0679
Epoch [80/500], Loss :54.5125
Epoch [90/500], Loss :53.9628
Epoch [100/500], Loss :53.4188
Epoch [110/500], Loss :52.8805
Epoch [120/500], Loss :52.3478
Epoch [130/500], Loss :51.8205
Epoch [140/500], Loss :51.2988
Epoch [150/500], Loss :50.7825
Epoch [160/500], Loss :50.2715
Epoch [170/500], Loss :49.7658
Epoch [180/500], Loss :49.2654
Epoch [190/500], Loss :48.7701
Epoch [200/500], Loss :48.2800
Epoch [210/500], Loss :47.7950
Epoch [220/500], Loss :47.3150
Epoch [230/500], Loss :46.8400
Epoch [240/500], Loss :46.3699
Epoch [250/500], Loss :45.9047
Epoch [260/500], Loss :45.4444
Epoch [270/500], Loss :44.9888
Epoch [280/500], Loss :44.5379
Epoch [290/500], Loss :44.0917
Epoch [300/500], Loss :43.6501
Epoch [310/500], Loss :43.2131
Epoch [320/500], Loss :42.7806
Epoch [330/500], 

In [123]:
pred = model(inputs)
print(pred)

tensor([[-0.7806],
        [-0.5677],
        [-0.6737],
        [-0.5895],
        [-0.8232],
        [-0.8885],
        [-0.7380],
        [-0.7172],
        [-0.5251],
        [-0.5895],
        [-0.8450],
        [-0.6964],
        [-0.5677],
        [-0.6301],
        [-1.0352],
        [-1.1431],
        [-0.9718],
        [-0.7806],
        [-0.8459],
        [-0.8876],
        [-0.6756],
        [-0.8450],
        [-0.9064],
        [-0.6330],
        [-0.6340],
        [-0.5261],
        [-0.6964],
        [-0.7598],
        [-0.7380],
        [-0.6112],
        [-0.5686],
        [-0.7172],
        [-1.0153],
        [-1.0787],
        [-0.5895],
        [-0.6945],
        [-0.8014],
        [-0.8232],
        [-0.5885],
        [-0.7172],
        [-0.8014],
        [-0.2904],
        [-0.6737],
        [-0.7390],
        [-0.8043],
        [-0.5677],
        [-0.8667],
        [-0.6529],
        [-0.8450],
        [-0.6954],
        [ 0.0339],
        [-0.0077],
        [ 0.

In [124]:
target

tensor([[5.1000],
        [4.9000],
        [4.7000],
        [4.6000],
        [5.0000],
        [5.4000],
        [4.6000],
        [5.0000],
        [4.4000],
        [4.9000],
        [5.4000],
        [4.8000],
        [4.8000],
        [4.3000],
        [5.8000],
        [5.7000],
        [5.4000],
        [5.1000],
        [5.7000],
        [5.1000],
        [5.4000],
        [5.1000],
        [4.6000],
        [5.1000],
        [4.8000],
        [5.0000],
        [5.0000],
        [5.2000],
        [5.2000],
        [4.7000],
        [4.8000],
        [5.4000],
        [5.2000],
        [5.5000],
        [4.9000],
        [5.0000],
        [5.5000],
        [4.9000],
        [4.4000],
        [5.1000],
        [5.0000],
        [4.5000],
        [4.4000],
        [5.0000],
        [5.1000],
        [4.8000],
        [5.1000],
        [4.6000],
        [5.3000],
        [5.0000],
        [7.0000],
        [6.4000],
        [6.9000],
        [5.5000],
        [6.5000],
        [5

In [403]:
nn.Linear

SyntaxError: invalid syntax (<ipython-input-403-2631effa1250>, line 1)